"""Regenerate paper/ra_macros.tex from the RuleArena result JSONLs.

Reads data/results/rulearena/{airline,tax}_core.jsonl, takes the LAST row per
(model, domain) at the largest n, and emits real formalize-once / plain / gap /
cost macros. No fabrication: only domains/models actually present are written.
Run: .venv/bin/python tools/fill_ra_macros.py
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, "src")
from symbol_scramble.config import model_spec  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "data" / "results" / "rulearena"
OUT = ROOT / "paper" / "ra_macros.tex"

SHORT = {"claude_opus48": "Opus", "claude_sonnet5": "Sonnet",
         "gpt55": "GPT", "gemini35_flash": "Gemini", "gemini31_pro": "GeminiPro"}


def cost(model, toks):
    s = model_spec(model)
    pt, ct = toks
    return (pt * s["cost_per_1k_in"] + ct * s["cost_per_1k_out"]) / 1000


def load(domain, level=0):
    """Latest usable row per model.

    For airline L0 a cell re-run with the plain completion ceiling raised
    supersedes the original. At the default 16,000 ceiling Sonnet spent the whole
    ceiling reasoning on many cases and returned nothing, which grading scored
    wrong; that is a harness outcome, not the model's accuracy. Cells that never
    approached the ceiling are unchanged by the re-run (tools/audit_truncation.py
    confirms none did, the next highest being 5,419 tokens per case)."""
    paths_ = [RES / f"{domain}_core.jsonl"]
    if domain == "airline" and level == 0:
        paths_.append(RES / "airline_ceil60k_core.jsonl")
    best = {}
    for p in paths_:
        if not p.exists():
            continue
        for line in p.read_text().splitlines():
            if not line.strip():
                continue
            r = json.loads(line)
            if r.get("level", 0) != level or r.get("code_extracted") is False:
                continue
            if r.get("plain_sc") not in (None, 1):
                continue  # headline is single-pass plain; SC rows live in *_matched
            if sum(r.get("per_case_plain_err", [])):
                continue  # incomplete cell: some plain cases never executed
            if r["model"] not in best or r["n"] >= best[r["model"]]["n"]:
                best[r["model"]] = r
    return best


def emit(lines, domain, prefix, rows):
    if not rows:
        return
    n = max(r["n"] for r in rows.values())
    lines.append(f"% ---- {domain} (n={n}) ----")
    lines.append(f"\\newcommand{{\\{prefix}N}}{{{n}}}")
    total = 0.0
    for mk, short in SHORT.items():
        if mk not in rows:
            continue
        r = rows[mk]
        cf, cp = cost(mk, r["form_tokens"]), cost(mk, r["plain_tokens"])
        total += cf + cp
        lines += [
            f"\\newcommand{{\\{prefix}{short}Form}}{{{r['formalize_once_acc']:.2f}}}",
            f"\\newcommand{{\\{prefix}{short}Plain}}{{{r['plain_acc']:.2f}}}",
            f"\\newcommand{{\\{prefix}{short}Gap}}{{{r['gap']:+.2f}}}",
            f"\\newcommand{{\\{prefix}{short}CostForm}}{{{cf:.2f}}}",
            f"\\newcommand{{\\{prefix}{short}CostPlain}}{{{cp:.2f}}}",
        ]
        # within-1% "band" metrics (present on runs that recorded them)
        if "formalize_band_acc" in r:
            lines.append(f"\\newcommand{{\\{prefix}{short}FormBand}}{{{r['formalize_band_acc']:.2f}}}")
        if "plain_band_acc" in r:
            lines.append(f"\\newcommand{{\\{prefix}{short}PlainBand}}{{{r['plain_band_acc']:.2f}}}")
    lines.append(f"\\newcommand{{\\{prefix}RunSpend}}{{\\${total:.2f}}}")
    lines.append("")


def main():
    lines = ["% Auto-generated by tools/fill_ra_macros.py — real numbers, do not hand-edit.",
             "\\newcommand{\\raNworked}{5}", ""]
    air = load("airline")
    tax = load("tax")
    emit(lines, "airline", "ra", air)      # ra* macros = airline (paper's main table)
    emit(lines, "tax", "raTax", tax)       # raTax* macros = tax
    # cost ratios, so the headline "N-Mx cheaper" claim cannot drift from the data
    ratios = {}
    for dom_, pref_ in (("airline", "ra"), ("tax", "raTax")):
        rs = []
        for mk, _ in SHORT.items():
            rws = air if dom_ == "airline" else tax
            if mk not in rws:
                continue
            r_ = rws[mk]
            cf, cp = cost(mk, r_["form_tokens"]), cost(mk, r_["plain_tokens"])
            if cf > 0:
                rs.append(cp / cf)
        if rs:
            ratios[dom_] = (min(rs), max(rs))
            lines.append(f"\\newcommand{{\\{pref_}RatioLo}}{{{min(rs):.0f}}}")
            lines.append(f"\\newcommand{{\\{pref_}RatioHi}}{{{max(rs):.0f}}}")
    # accuracy ranges, so "runs X--Y" in the prose cannot name the wrong endpoints
    for dom_, pref_ in (("airline", "ra"), ("tax", "raTax")):
        rws = air if dom_ == "airline" else tax
        fa = [rws[mk]["formalize_once_acc"] for mk in SHORT if mk in rws]
        pa = [rws[mk]["plain_acc"] for mk in SHORT if mk in rws]
        if fa:
            lines.append(f"\\newcommand{{\\{pref_}FormLo}}{{{min(fa):.2f}}}")
            lines.append(f"\\newcommand{{\\{pref_}FormHi}}{{{max(fa):.2f}}}")
            lines.append(f"\\newcommand{{\\{pref_}PlainLo}}{{{min(pa):.2f}}}")
            lines.append(f"\\newcommand{{\\{pref_}PlainHi}}{{{max(pa):.2f}}}")
    for dom_, pref_ in (("airline", "ra"), ("tax", "raTax")):
        rws = air if dom_ == "airline" else tax
        cfs = [cost(mk, rws[mk]["form_tokens"]) for mk in SHORT if mk in rws]
        cps = [cost(mk, rws[mk]["plain_tokens"]) for mk in SHORT if mk in rws]
        if cfs:
            lines.append(f"\\newcommand{{\\{pref_}CostFormLo}}{{{min(cfs):.2f}}}")
            lines.append(f"\\newcommand{{\\{pref_}CostFormHi}}{{{max(cfs):.2f}}}")
            lines.append(f"\\newcommand{{\\{pref_}CostPlainLo}}{{{min(cps):.2f}}}")
            lines.append(f"\\newcommand{{\\{pref_}CostPlainHi}}{{{max(cps):.2f}}}")
    if ratios:
        lines.append(f"\\newcommand{{\\raRatioAllLo}}"
                     f"{{{min(v[0] for v in ratios.values()):.0f}}}")
        lines.append(f"\\newcommand{{\\raRatioAllHi}}"
                     f"{{{max(v[1] for v in ratios.values()):.0f}}}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")
    print(f"airline models: {sorted(air)} | tax models: {sorted(tax)}")


if __name__ == "__main__":
    main()
