"""Emit paper/ra_ceiling_macros.tex: the completion-ceiling effect on per-case reasoning.

The published airline L0 cells ran the plain branch against a 16,000-token completion
ceiling. Sonnet averaged 10,073 completion tokens per case there and returned no answer
on many of them, which grading scored as wrong. Re-running the identical 90 cases with
the ceiling raised and nothing else changed isolates the effect.

Run:  python tools/fill_ra_ceiling.py
"""
import json
import math
import sys
from pathlib import Path

sys.path.insert(0, "tools")
sys.path.insert(0, "src")

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "data" / "results" / "rulearena"
OUT = ROOT / "paper" / "ra_ceiling_macros.tex"
OLD_CAP, NEW_CAP = 16000, 60000


def row(fname, mid, level=0):
    best = None
    for line in (RES / fname).read_text().splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if (r.get("model") == mid and r.get("n") == 90
                and r.get("level", 0) == level and r.get("plain_sc", 1) == 1):
            best = r
    return best


def mcnemar(b, c):
    n = b + c
    if n == 0:
        return 1.0
    k = min(b, c)
    return min(1.0, 2 * sum(math.comb(n, i) * 0.5 ** n for i in range(k + 1)))


old = row("airline_core.jsonl", "claude_sonnet5")
new = row("airline_ceil60k_core.jsonl", "claude_sonnet5")
o, n_ = old["per_case_plain"], new["per_case_plain"]
fixed = sum(1 for a, b in zip(n_, o) if a and not b)
broke = sum(1 for a, b in zip(n_, o) if b and not a)
p = mcnemar(fixed, broke)
delta = (fixed - broke) / len(o)

# how close every other published airline cell came to the old ceiling
per = {}
for line in (RES / "airline_core.jsonl").read_text().splitlines():
    if not line.strip():
        continue
    r = json.loads(line)
    if r.get("n") == 90 and r.get("plain_sc", 1) == 1 and r.get("plain_budget") == "3000":
        per[r["model"]] = r["plain_tokens"][1] / 90
others = max(v for k, v in per.items() if k != "claude_sonnet5")


def _opus_p(rec):
    """Paired McNemar exact p for one record, over cases that produced an answer."""
    pairs = [(f, c) for f, c in zip(rec["per_case_form"], rec["per_case_plain"])
             if not isinstance(f, str) and not isinstance(c, str)]
    b = sum(1 for f, c in pairs if f and not c)
    c = sum(1 for f, c in pairs if c and not f)
    n = b + c
    if n == 0:
        return 1.0
    return min(1.0, 2 * sum(math.comb(n, i) for i in range(min(b, c) + 1)) / 2 ** n)


opus_old = row("airline_core.jsonl", "claude_opus48")
opus_new = row("airline_ceil60k_core.jsonl", "claude_opus48")

L = ["% Completion-ceiling effect, generated by tools/fill_ra_ceiling.py.",
     f"\\newcommand{{\\raCeilCap}}{{{OLD_CAP:,}}}",
     f"\\newcommand{{\\raCeilNewCap}}{{{NEW_CAP:,}}}",
     f"\\newcommand{{\\raCeilTokens}}{{{per['claude_sonnet5']:,.0f}}}",
     f"\\newcommand{{\\raCeilOthersMax}}{{{others:,.0f}}}",
     f"\\newcommand{{\\raCeilPlainOld}}{{{old['plain_acc']:.2f}}}",
     f"\\newcommand{{\\raCeilPlainNew}}{{{new['plain_acc']:.2f}}}",
     f"\\newcommand{{\\raCeilDelta}}{{{delta:+.2f}}}",
     f"\\newcommand{{\\raCeilFixed}}{{{fixed}}}",
     f"\\newcommand{{\\raCeilBroken}}{{{broke}}}",
     f"\\newcommand{{\\raCeilP}}{{{p:.1e}}}".replace("e-0", "\\times 10^{-") + "}",
     f"\\newcommand{{\\raCeilGapOld}}{{{old['gap']:+.2f}}}",
     f"\\newcommand{{\\raCeilGapNew}}{{{new['gap']:+.2f}}}",
     f"\\newcommand{{\\raCeilOpusOld}}{{{opus_old['plain_acc']:.2f}}}",
     f"\\newcommand{{\\raCeilOpusNew}}{{{opus_new['plain_acc']:.2f}}}",
     # The Opus control is only a clean control on the plain branch. The rerun also
     # re-drew the program, so its formalize accuracy and its paired p-value moved
     # too, and the cell we report is the rerun's. Emit both so the appendix can say
     # so instead of quoting the plain half alone.
     f"\\newcommand{{\\raCeilOpusFormOld}}{{{opus_old['formalize_once_acc']:.2f}}}",
     f"\\newcommand{{\\raCeilOpusFormNew}}{{{opus_new['formalize_once_acc']:.2f}}}",
     f"\\newcommand{{\\raCeilOpusPOld}}{{{_opus_p(opus_old):.2f}}}",
     f"\\newcommand{{\\raCeilOpusPNew}}{{{_opus_p(opus_new):.3f}}}"]
OUT.write_text("\n".join(L) + "\n")
print(f"wrote {OUT}")
print(f"  Sonnet plain {old['plain_acc']:.3f} -> {new['plain_acc']:.3f} "
      f"({delta:+.3f}); fixed={fixed} broke={broke} p={p:.1e}")
print(f"  next highest cell: {others:,.0f} tokens/case; Opus "
      f"{opus_old['plain_acc']:.3f} -> {opus_new['plain_acc']:.3f}")
