"""Emit paper/ra_sweep_macros.tex: the airline difficulty sweep, generated.

The sweep table was hand-maintained, which is fragile now that every model is run
at every tier. This derives each cell from the stored per-case vectors, the same
way fill_ra_macros.py and fill_ra_ci.py do, so the table cannot drift from the data.

Significance is the exact two-sided McNemar test on discordant pairs, matching the
paper. Cells whose program never parsed (code_extracted false) are emitted as a
failure marker rather than a number -- a 0.00 there is a formalization failure, not
an accuracy measurement.

Run:  python tools/fill_ra_sweep.py
"""
import json
import math
import sys
from pathlib import Path

sys.path.insert(0, "src")
sys.path.insert(0, "tools")
from noanswer_report import no_answer_flags                         # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "data" / "results" / "rulearena"
OUT = ROOT / "paper" / "ra_sweep_macros.tex"

STEM = {"claude_opus48": "Opus", "claude_sonnet5": "Sonnet", "gpt55": "GPT",
        "gemini35_flash": "Flash", "gemini31_pro": "GemPro"}
WORD = {0: "Lzero", 1: "Lone", 2: "Ltwo"}
FILES = {0: "airline_core.jsonl", 1: "airline_L1_core.jsonl", 2: "airline_L2_core.jsonl"}
# cells run with the plain completion ceiling raised (see tools/run_sweep2.py)
CEIL = {("claude_sonnet5", 0): 60000, ("claude_opus48", 0): 60000,
        ("claude_sonnet5", 1): 60000, ("claude_sonnet5", 2): 60000,
        ("claude_opus48", 1): 60000, ("claude_opus48", 2): 60000}


def mcnemar_exact(b, c):
    n = b + c
    if n == 0:
        return 1.0
    k = min(b, c)
    return min(1.0, sum(math.comb(n, i) for i in range(k + 1)) / 2 ** n * 2)


def stars(p):
    return ("$^{***}$" if p < 0.001 else "$^{**}$" if p < 0.01
            else "$^{*}$" if p < 0.05 else "")


def cells(level):
    """Latest n=90 row per model at this level (later rows supersede earlier ones).

    At L0 a cell re-run with the ceiling raised supersedes the original: Sonnet
    was truncated at the default ceiling and its published plain accuracy is not
    a measurement of the model. Cells that never approached the ceiling are
    unaffected either way (see tools/audit_truncation.py)."""
    out = {}
    paths_ = [RES / FILES[level]]
    if level == 0:
        paths_.append(RES / "airline_ceil60k_core.jsonl")
    for fp in paths_:
        if not fp.exists():
            continue
        for line in fp.read_text().splitlines():
            if not line.strip():
                continue
            r = json.loads(line)
            if (r.get("n") == 90 and r.get("plain_sc", 1) == 1
                    and r.get("code_extracted")):
                out[r["model"]] = r
    return out


lines = ["% Airline difficulty sweep, generated by tools/fill_ra_sweep.py.",
         "% Do not hand-edit: every value is derived from the stored per-case vectors."]
for level in (0, 1, 2):
    for mid, row in sorted(cells(level).items()):
        stem = STEM.get(mid)
        if not stem:
            continue
        key = f"raSw{stem}{WORD[level]}"
        if not row.get("code_extracted"):
            for suf, val in (("Form", "--"), ("Plain", "--"), ("Gap", "--"), ("Sig", "")):
                lines.append(f"\\newcommand{{\\{key}{suf}}}{{{val}}}")
            continue
        # A case is excluded from the paired test when it was never answered:
        # an errored case (stored as a string) or one where the model spent its
        # whole completion ceiling reasoning and returned nothing. Counting either
        # as a wrong answer would credit formalize-once for a harness outcome.
        f, p = row["per_case_form"], row["per_case_plain"]
        # prefer the flags stored in the record (tools/backfill_noanswer.py); the
        # cache fallback exists only for records written before that field
        stored = row.get("per_case_no_answer")
        na = ([bool(x) for x in stored] if stored is not None
              else no_answer_flags(mid, level, CEIL.get((mid, level))))
        err = row.get("per_case_plain_err", [0] * len(p))
        pairs = [(a, c) for i, (a, c) in enumerate(zip(f, p))
                 if not isinstance(a, str) and not isinstance(c, str)
                 and not (i < len(na) and na[i]) and not err[i]]
        if sum(err):     # incomplete cell: the runner warned, do not table it
            print(f"  WARNING {mid} L{level}: {sum(err)}/{len(p)} plain cases never "
                  f"executed; cell is incomplete")
        b = sum(1 for a, c in pairs if a and not c)
        c = sum(1 for a, cc in pairs if cc and not a)
        gap = (b - c) / len(pairs)
        sig = stars(mcnemar_exact(b, c))
        lines.append(f"\\newcommand{{\\{key}Form}}{{{row['formalize_once_acc']:.2f}}}")
        lines.append(f"\\newcommand{{\\{key}Plain}}{{{row['plain_acc']:.2f}}}")
        lines.append(f"\\newcommand{{\\{key}Gap}}{{{gap:+.2f}}}")
        lines.append(f"\\newcommand{{\\{key}Sig}}{{{sig}}}")
        lines.append(f"\\newcommand{{\\{key}NoAns}}{{{sum(1 for x in na if x)}}}")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}  ({sum(1 for l in lines if 'newcommand' in l)} macros)")
