"""Macros and table for the fresh-input (contamination) check.

paper/ra_fresh_macros.tex, paper/tables/fresh.tex.

Refuses to emit anything if a cell did not finish. A cell abandoned by a credit cap
records its unrun cases in per_case_plain_err and would otherwise report as a
confident zero, which is how a spend limit turns into a finding.
"""
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "tools"))
from ra_cells import rows                                           # noqa: E402

SRC = ROOT / "data" / "results" / "rulearena" / "airline_fresh_core.jsonl"
MACROS = ROOT / "paper" / "ra_fresh_macros.tex"
TABLE = ROOT / "paper" / "tables" / "fresh.tex"
ORDER = ["claude_opus48", "claude_sonnet5", "gpt55", "gemini35_flash", "gemini31_pro"]
NAME = {"claude_opus48": "Opus~4.8", "claude_sonnet5": "Sonnet~5", "gpt55": "GPT-5.5",
        "gemini35_flash": "Gemini~3.5~Flash", "gemini31_pro": "Gemini~3.1~Pro"}
STEM = {"claude_opus48": "Opus", "claude_sonnet5": "Sonnet", "gpt55": "GPT",
        "gemini35_flash": "Gemini", "gemini31_pro": "GeminiPro"}


def mcnemar(b, c):
    n = b + c
    if n == 0:
        return 1.0
    return min(1.0, sum(math.comb(n, i) for i in range(min(b, c) + 1)) / 2 ** n * 2)


def tango(b, c, n, z=1.96):
    def score(d):
        A, B = 2 * n, -b - c + (2 * n - b + c) * d
        Cc = -c * d * (1 - d)
        q = (-B + math.sqrt(max(B * B - 4 * A * Cc, 0.0))) / (2 * A)
        var = n * (2 * q + d * (1 - d))
        return (b - c - n * d) / math.sqrt(var) if var > 0 else math.inf

    def solve(lo, hi, t):
        for _ in range(200):
            m = (lo + hi) / 2
            lo, hi = (m, hi) if score(m) - t > 0 else (lo, m)
        return (lo + hi) / 2

    pt = (b - c) / n
    return pt, solve(-0.999, pt, z), solve(pt, 0.999, -z)


def paired(r):
    f, p = r["per_case_form"], r["per_case_plain"]
    err = r.get("per_case_plain_err", [0] * len(p))
    keep = [i for i in range(len(p)) if not err[i]]
    return (sum(1 for i in keep if f[i] and not p[i]),
            sum(1 for i in keep if p[i] and not f[i]), len(keep))


def stars(p):
    return "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else ""


def main():
    fresh = {}
    for line in SRC.read_text().splitlines():
        if line.strip():
            r = json.loads(line)
            if r.get("n") == 90 and r.get("code_extracted"):
                fresh[r["model"]] = r
    bad = [m for m, r in fresh.items() if sum(r.get("per_case_plain_err", []))]
    missing = [m for m in ORDER if m not in fresh]
    if bad or missing:
        print("REFUSING to emit macros -- unfinished:", bad, "missing:", missing)
        return 1

    pub, out, body = rows("airline", 0), [], []
    fgaps, pgaps = [], []
    for mid in ORDER:
        fr, pr = fresh[mid], pub[mid]
        fb, fc, fn = paired(fr)
        pb, pc, pn = paired(pr)
        fg, lo, hi = tango(fb, fc, fn)
        pg, _, _ = tango(pb, pc, pn)
        fp = mcnemar(fb, fc)
        fgaps.append(fg)
        pgaps.append(pg)
        st = STEM[mid]
        out += [(f"raFr{st}Form", f"{fr['formalize_once_acc']:.2f}"),
                (f"raFr{st}Plain", f"{fr['plain_acc']:.2f}"),
                (f"raFr{st}Gap", f"{fg:+.2f}{stars(fp)}"),
                (f"raFr{st}Lo", f"{lo:+.2f}"), (f"raFr{st}Hi", f"{hi:+.2f}"),
                (f"raFr{st}P", f"{fp:.3f}"),
                (f"raFr{st}PubGap", f"{pg:+.2f}")]
        body.append(f"    {NAME[mid]} & {pr['formalize_once_acc']:.2f} & "
                    f"{pr['plain_acc']:.2f} & ${pg:+.2f}$ & "
                    f"{fr['formalize_once_acc']:.2f} & {fr['plain_acc']:.2f} & "
                    f"${fg:+.2f}$$^{{{stars(fp)}}}$ \\\\")
    ff = [float(dict(out)[f"raFr{STEM[m]}Form"]) for m in ORDER]
    pf = [pub[m]["formalize_once_acc"] for m in ORDER]
    out += [("raFrFormLo", f"{min(ff):.2f}"), ("raFrFormHi", f"{max(ff):.2f}"),
            ("raFrPubFormLo", f"{min(pf):.2f}"), ("raFrPubFormHi", f"{max(pf):.2f}"),
            ("raFrNpos", str(sum(1 for g in fgaps if g > 0))),
            ("raFrNneg", str(sum(1 for g in fgaps if g < 0))),
            ("raFrNsig", str(sum(1 for k, v in out if k.endswith("Gap") and "*" in v))),
            ("raFrPubNpos", str(sum(1 for g in pgaps if g > 0))),
            ("raFrGapLo", f"{min(fgaps):+.2f}"), ("raFrGapHi", f"{max(fgaps):+.2f}"),
            ("raFrMatchDev", "11")]
    MACROS.write_text("% generated by tools/fill_ra_fresh.py -- do not edit\n"
                      + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in out))
    TABLE.write_text(
        "% generated by tools/fill_ra_fresh.py -- do not edit\n"
        "\\begin{tabular}{lcccccc}\n    \\toprule\n"
        "    & \\multicolumn{3}{c}{Public inputs} & "
        "\\multicolumn{3}{c}{Generated inputs}\\\\\n"
        "    \\cmidrule(lr){2-4}\\cmidrule(lr){5-7}\n"
        "    Model & Formalize & Plain & Gap & Formalize & Plain & Gap \\\\\n"
        "    \\midrule\n" + "\n".join(body) + "\n    \\bottomrule\n\\end{tabular}\n")
    print(f"wrote {MACROS.name} ({len(out)} macros) and tables/{TABLE.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
