"""Emit paper/ra_ci_macros.tex: 95% confidence intervals on the *paired difference*
(formalize-once minus plain) for every reported cell, plus the tightest bound the
tied cells place on a plain advantage.

Interval: Tango (1998) score interval for the difference of paired proportions,
not a percentile bootstrap. The design is paired and the reported test is
McNemar's, so the estimand is the paired difference; and on paired binary data the
bootstrap degenerates at the boundary, returning a zero-width interval when there
are no discordant pairs and an interval that appears to exclude zero where the
exact test does not reject. Tango behaves correctly in both cases.

Run:  python tools/fill_ra_ci.py
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / "data" / "results" / "rulearena"
OUT = ROOT / "paper" / "ra_ci_macros.tex"

SHORT = {"claude_opus48": "Opus", "claude_sonnet5": "Sonnet", "gpt55": "GPT",
         "gemini35_flash": "Gemini", "gemini31_pro": "GeminiPro"}
SWEEP_SHORT = {"gemini31_pro": "GemPro", "gpt55": "GPT", "gemini35_flash": "Flash"}


def tango(b, c, n, z=1.96):
    """Tango (1998) score interval for the paired difference p1 - p2."""
    def score(d):
        A = 2 * n
        B = -b - c + (2 * n - b + c) * d
        C = -c * d * (1 - d)
        q = (-B + math.sqrt(max(B * B - 4 * A * C, 0.0))) / (2 * A)
        var = n * (2 * q + d * (1 - d))
        if var <= 0:
            return math.inf if (b - c - n * d) > 0 else -math.inf
        return (b - c - n * d) / math.sqrt(var)

    def solve(lo, hi, target):
        for _ in range(200):
            mid = (lo + hi) / 2
            if score(mid) - target > 0:
                lo = mid
            else:
                hi = mid
        return (lo + hi) / 2

    point = (b - c) / n
    return point, solve(-0.999, point, z), solve(point, 0.999, -z)


def cells_legacy(fname, level=0):
    out = {}
    p = RES / fname
    if not p.exists():
        return out
    for line in p.read_text().splitlines():
        if not line.strip():
            continue
        r = json.loads(line)
        if (r.get("per_case_form") and r.get("level", 0) == level
                and r.get("code_extracted") is not False
                and r.get("plain_sc") in (None, 1)):
            out[r["model"]] = r
    return out


def interval(r, domain="airline", level=0):
    """Interval over cases that produced an answer (see tools/ra_cells.py)."""
    import sys as _s
    _s.path.insert(0, "tools")
    from ra_cells import paired
    b, c, n = paired(r, domain, level)
    return tango(b, c, n)


lines = ["% Auto-generated by tools/fill_ra_ci.py: Tango (1998) score intervals",
         "% on the paired difference. Do not hand-edit."]
worst_lower = 0.0          # how much of a plain advantage the tied cells still allow

import sys as _sys
_sys.path.insert(0, "tools")
from ra_cells import rows as _rows                                  # noqa: E402

for domain, prefix, short in [("airline", "raCI", SHORT),
                              ("tax", "raTaxCI", SHORT)]:
    for mid, key in short.items():
        rws = _rows(domain, 0)
        if mid not in rws:
            continue
        pt, lo, hi = interval(rws[mid], domain, 0)
        lines.append(f"\\newcommand{{\\{prefix}{key}}}{{[{lo:+.2f},\\,{hi:+.2f}]}}")
        worst_lower = min(worst_lower, lo)

for fname, lv in [("airline_L1_core.jsonl", 1), ("airline_L2_core.jsonl", 2)]:
    rws = _rows("airline", lv)
    for mid, key in SWEEP_SHORT.items():
        if mid not in rws:
            continue
        pt, lo, hi = interval(rws[mid], "airline", lv)
        word = {1: "Lone", 2: "Ltwo"}[lv]   # control sequences cannot contain digits
        lines.append(f"\\newcommand{{\\raSwCI{key}{word}}}{{[{lo:+.2f},\\,{hi:+.2f}]}}")

lines.append(f"\\newcommand{{\\raCIworstPlain}}{{{abs(worst_lower):.2f}}}")
OUT.write_text("\n".join(lines) + "\n")
print("wrote", OUT)
print(f"tightest bound: no cell's interval admits a plain advantage larger than "
      f"{abs(worst_lower):.2f}")
