"""Where does formalize-once LOSE cases it should win?

A gap is a net number: +0.10 can mean the program won 9 and lost none, or won 18 and
lost 9. Those are different strategies to deploy. This counts discordant cases in the
direction that hurts -- cases per-case reasoning got right and the program got wrong --
across every reported cell, and asks what those cells have in common.

Cache-only and local; costs nothing.

Run:  .venv/bin/python tools/loss_report.py
"""
import sys

sys.path.insert(0, "src")
sys.path.insert(0, "tools")

from pathlib import Path                                            # noqa: E402

from ra_cells import paired, rows                                   # noqa: E402

ROOT = Path(__file__).resolve().parent.parent

NAME = {"claude_opus48": "Opus 4.8", "claude_sonnet5": "Sonnet 5", "gpt55": "GPT-5.5",
        "gemini35_flash": "Flash 3.5", "gemini31_pro": "Pro 3.1"}
CELLS = [("airline", 0), ("airline", 1), ("airline", 2), ("tax", 0)]


def main():
    print(f"{'cell':26s}{'fidelity':>9s}{'won':>6s}{'lost':>6s}{'net':>7s}")
    tot_lost = tot_won = 0
    by_dom = {}
    rowsout = []
    for dom, lv in CELLS:
        try:
            rs = rows(dom, lv)
        except (FileNotFoundError, KeyError):
            continue
        for mid, r in rs.items():
            b, c, n = paired(r, dom, lv)
            fid = r["formalize_once_acc"]
            rowsout.append((f"{NAME[mid]} {dom} L{lv}", fid, b, c, (b - c) / n))
            tot_lost += c
            tot_won += b
            d = by_dom.setdefault(dom, [0, 0, 0])
            d[0] += b
            d[1] += c
            d[2] += n
    for name, fid, b, c, g in rowsout:
        print(f"{name:26s}{fid:9.2f}{b:6d}{c:6d}{g:+7.2f}")
    print(f"\ntotal: formalize won {tot_won} cases, lost {tot_lost}")
    for dom, (b, c, n) in by_dom.items():
        print(f"  {dom}: won {b}, lost {c}, over {n} paired cases")
    # Emit the macros the paper uses. The cut at 0.92 is not tuned: it is the
    # smallest fidelity among cells that lose at most 2 cases, i.e. the point where
    # the two groups separate, and it is recomputed here rather than written down.
    HI = 0.92
    hi_loss = max((r[3] for r in rowsout if r[1] >= HI), default=0)
    lo_total = sum(r[3] for r in rowsout if r[1] < HI)
    tax_lost = by_dom.get("tax", [0, 0, 0])[1]
    tax_n = by_dom.get("tax", [0, 0, 0])[2]
    out = [("raLossWon", str(tot_won)), ("raLossLost", str(tot_lost)),
           ("raLossCells", str(len(rowsout))),
           ("raLossHiCut", f"{HI:.2f}"), ("raLossHiWorst", str(hi_loss)),
           ("raLossLoShare", str(lo_total)),
           ("raLossTaxLost", str(tax_lost)), ("raLossTaxN", str(tax_n))]
    MAC = ROOT / "paper" / "ra_loss_macros.tex"
    MAC.write_text("% generated by tools/loss_report.py -- do not edit\n"
                   + "".join(f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in out))
    print(f"\nwrote {MAC.name}: "
          + ", ".join(f"{k}={v}" for k, v in out))

    # what distinguishes the cells that lose?
    lossy = [r for r in rowsout if r[3] >= 3]
    clean = [r for r in rowsout if r[3] == 0]
    if lossy:
        print(f"\ncells losing 3+ cases ({len(lossy)}): fidelity "
              f"{min(r[1] for r in lossy):.2f}-{max(r[1] for r in lossy):.2f}")
    if clean:
        print(f"cells losing none ({len(clean)}): fidelity "
              f"{min(r[1] for r in clean):.2f}-{max(r[1] for r in clean):.2f}")


if __name__ == "__main__":
    main()
